import { chromium } from 'playwright';
const b = await chromium.launch({ args: ['--use-angle=metal','--enable-unsafe-swiftshader','--ignore-gpu-blocklist','--mute-audio'] });
const p = await b.newPage({ viewport: { width: 1920, height: 1080 } });
await p.route('**/@vite/client', (r) => r.fulfill({ status: 200, contentType: 'application/javascript', body: 'export const createHotContext = () => ({ accept(){}, prune(){}, dispose(){}, invalidate(){}, on(){}, send(){} }); export const updateStyle = () => {}; export const removeStyle = () => {}; export const injectQuery = (u) => u;' }));
await p.goto('http://localhost:5273/?q=ultra', { waitUntil: 'load' });
await p.waitForFunction(() => !!window.__game, null, { timeout: 90000 });
const out = await p.evaluate(async () => {
  const g = window.__game;
  const wait = (ms) => new Promise((r) => setTimeout(r, ms));
  g.state.elements = ['fire','water','nature','earth','light','dark'];
  g.state.pendingElementPicks = 0; g.state.gold = 9e9;
  g.hud.closeElementPicker(); g.state.phase = 'prep'; g.hud.refreshBuildBar();
  const MAZE = [['fire',10,3],['fire',14,3],['water',8,5],['nature',12,5],['earth',16,5],['light',6,7],['dark',10,7],['steam',14,7],['ice',18,7],['magma',8,9],['poison',12,9],['crystal',16,9],['blaze',6,11],['void',10,11],['magic',14,11],['life',18,11],['water',8,13],['nature',12,13],['earth',16,13],['light',10,15],['dark',14,15]];
  for (const [k,c,r] of MAZE) g.build(k,c,r);
  await wait(2000);
  const T = () => g.pipeline.renderer.info.render.triangles;
  const C = () => g.pipeline.renderer.info.render.calls;
  const on = { t: T(), c: C() };
  g.towers.group.visible = false; await wait(800);
  const off = { t: T(), c: C() };
  g.towers.group.visible = true;
  return { total: on.t, towerTris: on.t - off.t, totalCalls: on.c, towerCalls: on.c - off.c, towers: g.towers.towers.length };
});
console.log(JSON.stringify(out, null, 2));
await b.close();
